csertant/szikapp

lib/utils/exceptions.dart
=> Alap- és IOExceptionök létrehozása

lib/utils/settings.dart, pubspec.yaml
=> Settings osztály megírása 

lib/models/cleaning_period.dart, lib/models/cleaning_period.g.dart, lib/models/tasks.dart, lib/models/tasks.g.dart, lib/utils/io.dart, pubspec.yaml
...bár teszteletlen.
closes #8
@speter46 csak nyugodtan fogadd el (zöld gomb -> approve)
=> IO osztály kész

.github/CODEOWNERS, .github/workflows/deploy.yml, .github/workflows/test.yml, README.md
Default branch váltás miatt.
Remélhetőleg megoldja #24-et (szerk: cst)
=> Szinkronizálás

lib/utils/user.dart
closes #13 
Az engedélykezelés finomítására majd a továbbiakban kerül sor. (#22 segítségével; szerk: SM)
=> User osztály kész

android/app/src/main/AndroidManifest.xml, lib/utils/io.dart
=> IO függvények integrálása

lib/models/permission.dart, lib/utils/io.dart, lib/utils/user.dart
=> Engedélyek hozzáadása

ios/Runner/Info.plist, lib/business/contacts.dart, pubspec.yaml
=> Contacts osztály létrehozása

lib/business/contacts.dart
Ezt én néztem be, mea culpa...
=> Exception nevezéktan

lib/business/janitor.dart
closes #20 
@sarvarimark deleteTask és addTask IO-val való kommunikációját különös figyelemmel nézd át légyszi:) a többi remélem, nagyjából jó
=> janitor osztály megírása

assets/translations/en.json, assets/translations/hu.json, ios/Runner/Info.plist, lib/main.dart, lib/pages/home_page.dart, lib/pages/menu_page.dart, lib/pages/profile_page.dart, lib/pages/settings_page.dart, lib/pages/signin_page.dart
Technológia: Flutter Navigation 1.0 a #41 issueban leírtakkal ellentétben.
=> Navigációs séma hozzáadása

lib/business/janitor.dart, lib/utils/io.dart, lib/utils/settings.dart, lib/utils/user.dart
=> IO endpointokhoz igazítása

lib/business/reservation.dart
closes #31 
@sarvarimark 
@csertant
=> reservetion osztály - teremfoglalások

android/app/build.gradle, android/build.gradle, lib/main.dart, pubspec.yaml
Érdemes lenne most hozzáadni, hogy mire lesznek valódi képernyőink tudjuk detektálni a rendszeres hibákat és összeomlásokat.
=> Firebase szolgáltatások konfigurációja

lib/business/reservation.dart
resolves #49 
Ugyanitt: ez a fajta Edit fgv megvalósítás nekem jobban tetszik, mint az idáigiak, főleg, mert eggyel kevesebb paraméterrel dolgoznánk. Esetleg a többit is ilyen formátumba helyezzem?
=> Kimaradt fgv megvalóstása

lib/business/kitchen_cleaning.dart
=> konyhataka-csere kész

assets/translations/en.json, assets/translations/hu.json, lib/business/contacts.dart, lib/business/janitor.dart, lib/pages/contacts_page.dart, lib/pages/home_page.dart
=> Keresőmező

lib/business/janitor.dart, lib/business/kitchen_cleaning.dart, lib/business/poll.dart, lib/business/reservation.dart
=> refresh függvények átírása

lib/models/cleaning_exchange.g.dart, lib/models/cleaning_period.g.dart, lib/models/goodtoknow.dart, lib/models/goodtoknow.g.dart, lib/models/group.g.dart, lib/models/preferences.g.dart, lib/models/resource.g.dart, lib/models/tasks.g.dart, lib/models/user_data.g.dart, lib/utils/io.dart, pubspec.yaml
=> GoodToKnow modell és IO függvények hozzáadása

README.md, android/app/build.gradle, lib/business/reservation_manager.dart, lib/components/app/bottom_navigation_bar.dart, pubspec.yaml
A foglalásoknál és a szavazásoknál javítottam a navigációt, így már a menedzserek a belső képernyőikről is engedik a kilépést, mikor a menüsávon ablakot választunk.
=> Beágyazott navigáció javítása

assets/translations/en.json, assets/translations/hu.json, lib/business/kitchen_cleaning_manager.dart, lib/models/cleaning_exchange.dart, lib/models/cleaning_exchange.g.dart, lib/screens/cleaning/cleaning_apply_view.dart, lib/screens/cleaning/cleaning_exchanges_view.dart, lib/screens/cleaning/cleaning_screen.dart, lib/screens/cleaning/cleaning_tasks_view.dart, lib/utils/io.dart, lib/utils/methods.dart, pubspec.yaml
=> Kc calendar m
